import{a as S,S as q,i as c}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="53481341-e80ac65b3d507f200d27055db",P="https://pixabay.com/api/";async function u(n,r=1){const s={key:v,q:n,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15};return(await S.get(P,{params:s})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),B=new q(".gallery a");function h(n){const r=n.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:i,comments:b,downloads:w})=>`
        <li class="gallery-item">
          <a href="${o}">
            <img src="${s}" alt="${e}" />
            <div class="info">
              <p><b>Likes</b><span>${t}</span></p>
              <p><b>Views</b><span>${i}</span></p>
              <p><b>Comments</b><span>${b}</span></p>
              <p><b>Downloads</b><span>${w}</span></p>
            </div>
          </a>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",r),B.refresh()}function E(){p.innerHTML=""}function g(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function M(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}const $=document.querySelector(".form"),R=document.querySelector(".load-more");let d="",a=1,l=0;$.addEventListener("submit",O);R.addEventListener("click",x);async function O(n){n.preventDefault();const s=new FormData(n.target).get("search-text").trim();if(!s){c.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=s,a=1,E(),L(),g();try{const o=await u(d,a);l=o.totalHits,o.hits.length===0?c.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(h(o.hits),o.hits.length<l&&a*15<l&&M())}catch{c.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"})}finally{y()}}async function x(){a+=1,g();try{const n=await u(d,a);h(n.hits);const r=document.querySelector(".gallery-item");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}a*15>=l&&(L(),c.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
